\ProvidesClass{paradox}

\LoadClass{book}

\RequirePackage[utf8]{inputenc}
\RequirePackage{geometry}
\RequirePackage{graphicx}
\RequirePackage{txfonts}
\RequirePackage[usenames,dvipsnames,svgnames,table]{xcolor}

\graphicspath{{./img/}}

% Lexicon
\newcommand*{\ParadoxSpaceRPG}{\emph{Paradox Space RPG}}
\newcommand*{\GM}{Narrator}
\newcommand*{\TN}{Success Threshold}

% Glyphs and icons
\newcommand*{\gameterm}[1]{\emph{#1}}
\newcommand*{\spade}{$\spadesuit$}
\newcommand*{\heart}{\textcolor{red}{$\varheartsuit$}}
\renewcommand*{\diamond}{\textcolor{red}{$\Diamondblack$}}
\newcommand*{\club}{$\clubsuit$}

\endinput
