\ProvidesClass{paradox}

\LoadClass{book}

\RequirePackage[utf8]{inputenc}
\RequirePackage{geometry}
\RequirePackage{graphicx}
\RequirePackage{txfonts}
\RequirePackage[usenames,dvipsnames,svgnames,table]{xcolor}

\graphicspath{ {./wip/} }

\newcommand*{\ParadoxSpaceRPG}{\emph{Paradox Space RPG}}
\newcommand*{\spade}{$\spadesuit$}
\newcommand*{\heart}{\textcolor{red}{$\varheartsuit$}}
\renewcommand*{\diamond}{\textcolor{red}{$\Diamondblack$}}
\newcommand*{\club}{$\clubsuit$}

\endinput
